### ISSUE TITLE
Add licence information

### ISSUE THREAD

**Issue by rfelten** [bcopeland/speccy#2]
Hi Bob,

I'm working with your code for a while now, assuming that it is FOSS. But I've just realized that information about the licence is missing. Can you add information about the licence of the code? 

It would be great if Speccy could use GPLv3! (Rather than for instance MIT, see [ZMQ Guide chapter 6](http://zguide.zeromq.org/page:chapter6#The-Importance-of-Contracts) on that topic).

BR
Robert

**Comment by bcopeland** [comment]
On Sat, Feb 06, 2016 at 04:35:01AM -0800, Robert Felten wrote:

> Hi Bob,
> 
> I'm working with your code for a while now, assuming that it is FOSS But I've just realized that information about the licence is missing Can you add information about the licence of the code? 
> 
> It would be great if Speccy could use GPLv3! (Rather than for instance MIT, see [ZMQ Guide chapter 6](http://zguidezeromqorg/page:chapter6#The-Importance-of-Contracts) on that topic)
> 
> BR
> Robert

Thanks, I'll add a license file for GPL v2 or later.

## 

Bob Copeland %% http://bobcopeland.com/

**Comment by rfelten** [comment]
Fixed in 11f90b30602325966ea531fa08fae0bbfd7fe567
Thx!
