### ISSUE TITLE
Using example_offline_analysis.py

### ISSUE THREAD

**Issue by HenryGiraldo** [bcopeland/speccy#6]
I'm trying to use example_offline_analysis.py.

I have created a folder called spectral_data filled with multiples examples "*.bin" and I get always the same return:
```

processing './spectral_data/ejemplo.bin':
Traceback (most recent call last):
  File "./example_offline_analysis.py", line 29, in <module>
    main()
  File "./example_offline_analysis.py", line 26, in main
    process("./spectral_data/"+fn)
  File "./example_offline_analysis.py", line 13, in process
    device_id, ts, sample_data = cPickle.load(f)
cPickle.UnpicklingError: invalid load key, ''.
```

I have this return even using your example stored in the samples folder.

**Comment by bcopeland** [comment]
Hi!

This probably bitrotted somewhat.  One problem is that pickle format
isn't stable between python versions.  I haven't had time to look into
this, but if you have the time it would a great project to use some
other serialization format!

On Thu, Jan 31, 2019 at 03:42:31AM -0800, hgiraldos wrote:
> I'm trying to use example_offline_analysis.py.
> 
> I have created a folder called spectral_data filled with multiples examples "*.bin" and I get always the same return:
> ```
> 
> processing './spectral_data/ejemplo.bin':
> Traceback (most recent call last):
>   File "./example_offline_analysis.py", line 29, in <module>
>     main()
>   File "./example_offline_analysis.py", line 26, in main
>     process("./spectral_data/"+fn)
>   File "./example_offline_analysis.py", line 13, in process
>     device_id, ts, sample_data = cPickle.load(f)
> cPickle.UnpicklingError: invalid load key, ''.
> ```
> 
> I have this return even using your example stored in the samples folder.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bcopeland/speccy/issues/6

-- 
Bob Copeland %% https://bobcopeland.com/
